### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by Heromine** [Heromine/tempapp1#8]
11-25 17:39:34.176 30067-30067/notes.service.com.servicenotes E/SQLiteLog: (1) no such table: note
11-25 17:39:34.177 30067-30067/notes.service.com.servicenotes E/NoteSQLiteDAO: Could not complete fetch all
                                                                               android.database.sqlite.SQLiteException: no such table: note (code 1): , while compiling: SELECT _id, title, content, created_at, updated_at FROM note
                                                                                   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
                                                                                   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
                                                                                   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                                   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                                   at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                                   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                                   at notes.service.com.servicenotes.data.dao.impl.sqlite.NoteSQLiteDAO.fetchAll(NoteSQLiteDAO.java:56)
                                                                                   at notes.service.com.servicenotes.data.dao.impl.sqlite.NoteSQLiteDAO.fetchAll(NoteSQLiteDAO.java:24)
                                                                                   at notes.service.com.servicenotes.MainActivity.setupNotesAdapter(MainActivity.java:236)
                                                                                   at notes.service.com.servicenotes.MainActivity.onCreate(MainActivity.java:68)
                                                                                   at android.app.Activity.performCreate(Activity.java:5990)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                                   at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
11-25 17:39:34.178 30067-30067/notes.service.com.servicenotes D/AndroidRuntime: Shutting down VM
11-25 17:39:34.178 30067-30067/notes.service.com.servicenotes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: notes.service.com.servicenotes, PID: 30067
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{notes.service.com.servicenotes/notes.service.com.servicenotes.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                                    at notes.service.com.servicenotes.MainActivity.setupNotesAdapter(MainActivity.java:236)
                                                                                    at notes.service.com.servicenotes.MainActivity.onCreate(MainActivity.java:68)
                                                                                    at android.app.Activity.performCreate(Activity.java:5990)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by Heromine** [comment]
stupid me
